name: github-actions
on: pull_request
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: clone-repo-windows
        run: git clone https://github.com/mucsci-students/2024sp-420-PythonA .
      - name: ls-windows
        run: ls
      - name: make-venv-directory-windows
        run: mkdir venv
      - name: ls-windows2
        run: ls
      - name: build-project-windows
        run: py build.py
      - name: install-pytest-windows
        run: pip install pytest
      - name: install-pytest-cov-windows
        run: pip install pytest-cov
      - name: unit-tests-windows
        run: pytest --cov-fail-under=100 .

  mac:
    runs-on: macos-latest
    steps:
      - name: clone-repo-mac
        run: git clone https://github.com/mucsci-students/2024sp-420-PythonA .
      - name: ls-mac
        run: ls
      - name: create-venv-mac
        run: sudo python3 -m venv venv
      - name: activate-venv-mac
        run: source venv/bin/activate
      - name: build-project-mac
        run: python3 build.py
      - name: install-pytest-mac
        run: pip install pytest
      - name: install-pytest-cov-mac
        run: pip install pytest-cov
      - name: unit-tests-mac
        run: pytest --cov-fail-under=100 .

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: clone-repo-linux
        run: git clone https://github.com/mucsci-students/2024sp-420-PythonA .
      - name: ls-linux
        run: ls
      - name: create-venv-linux
        run: sudo python -m venv venv
      - name: activate-venv-linux
        run: source venv/bin/activate
      - name: build-project-linux
        run: python build.py
      - name: install-pytest-linux
        run: pip install pytest
      - name: install-pytest-cov-linux
        run: pip install pytest-cov
      - name: unit-tests-linux
        run: pytest --cov-fail-under=100 .