name: github-actions
on: pull_request
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: windows-clone-repo
        run: git clone https://github.com/mucsci-students/2024sp-420-PythonA
      - name: windows-cd
        run: cd 2024sp-420-PythonA/src/test
      - name: install-pytest-windows
        run: pip install pytest
      - name: unit-tests-windows
        run: pytest

  mac:
    runs-on: macos-latest
    steps:
      - name: mac-clone-repo
        run: git clone https://github.com/mucsci-students/2024sp-420-PythonA
      - name: mac-cd
        run: cd 2024sp-420-PythonA/src/test
      - name: install-pytest-mac
        run: pip install pytest
      - name: unit-tests-mac
        run: pytest

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: linux-clone-repo
        run: git clone https://github.com/mucsci-students/2024sp-420-PythonA
      - name: linux-cd
        run: cd 2024sp-420-PythonA/src/test
      - name: install-pytest-linux
        run: pip install pytest
      - name: unit-tests-linux
        run: pytest
