name: github-actions
on: pull_request
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: clone-repo-windows
        run: git clone https://github.com/mucsci-students/2024sp-420-PythonA
      - name: cd-windows
        run: cd 2024sp-420-PythonA
      - name: build-project-windows
        run: py build.py
      - name: install-pytest-windows
        run: pip install pytest
      - name: install-pytest-cov-windows
        run: pip install pytest-cov
      - name: unit-tests-windows
        run: pytest --cov-fail-under=100 .

  mac:
    runs-on: macos-latest
    steps:
      - name: clone-repo-mac
        run: git clone https://github.com/mucsci-students/2024sp-420-PythonA
      - name: cd-mac
        run: cd 2024sp-420-PythonA
      - name: build-project-mac
        run: python3 build.py
      - name: install-pytest-mac
        run: pip install pytest
      - name: install-pytest-cov-mac
        run: pip install pytest-cov
      - name: unit-tests-mac
        run: pytest --cov-fail-under=100 .

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: linux-ls
        run: ls -a
      - name: clone-repo-linux
        run: git clone https://github.com/mucsci-students/2024sp-420-PythonA .
      - name: linux-ls2
        run: ls -a
      - name: check-python-version-linux
        run: python --version
      - name: check-git-version-linux
        run: git --version
      - name: build-project-linux
        run: python build.py
      - name: install-pytest-linux
        run: pip install pytest
      - name: install-pytest-cov-linux
        run: pip install pytest-cov
      - name: unit-tests-linux
        run: pytest --cov-fail-under=100 .