name: github-actions
on: pull_request
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: windows-ls
        run: ls
      - name: build-project-windows
        run: py -m pip install -e .
      - name: install-pytest-cov-windows
        run: pip install pytest-cov
      - name: unit-tests-windows
        run: pytest --cov-fail-under=80 .

  mac:
    runs-on: macos-latest
    steps:
      - name: mac-ls
        run: ls
      - name: build-project-mac
        run: python3 -m pip install -e .
      - name: install-pytest-cov-mac
        run: pip install pytest-cov
      - name: unit-tests-mac
        run: pytest --cov-fail-under=80 .

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: linux-ls
        run: ls
      - name: build-project-linux
        run: python -m pip install -e .
      - name: install-pytest-cov-linux
        run: pip install pytest-cov
      - name: unit-tests-linux
        run: pytest --cov-fail-under=80 .