name: github-actions2
on: pull_request
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Project and Dependencies
        run: |
          pip install -e .
          pip install coverage
      - name: Coverage Report
        run: |
          coverage run -m pytest
          coverage report --fail-under=100 --omit='*/mvc_controller/*','*/mvc_view/*' --show-missing /Users/runner/work/2024sp-420-PythonA/2024sp-420-PythonA/src/umleditor/mvc_model/*
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Project and Dependencies
        run: |
          pip install -e .
          pip install coverage

      - name: Coverage Report
        run: |
          coverage run -m pytest
          coverage report --fail-under=100 --omit='*/mvc_controller/*','*/mvc_view/*' --show-missing /Users/runner/work/2024sp-420-PythonA/2024sp-420-PythonA/src/umleditor/mvc_model/*
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Project and Dependencies
        run: |
          pip install -e .
          pip install pytest-cov

      - name: Install PyQt6 dependencies
        run: sudo apt-get update && sudo apt-get install -y libegl1-mesa libxkbcommon-x11-0
      - name: Coverage Report
        run: |
          coverage run -m pytest
          coverage report --fail-under=100 --omit='*/mvc_controller/*','*/mvc_view/*' --show-missing /Users/runner/work/2024sp-420-PythonA/2024sp-420-PythonA/src/umleditor/mvc_model/*

